# Generated by Django 4.1.6 on 2023-12-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_room_number_item_created_at_item_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.IntegerField(),
        ),
    ]
